NAME = libftprintf.a

CC = cc
CFLAFS = -Wall -Wextra -Werror

SRCS = ft_printf.c

all: $(NAME)

$(NAME): $(SRCS) libftprintf.h
	$(CC) $(COMPILE_FLAGS) $(SRCS) -o $(NAME)

clean:
	rm -f $(NAME)

re: clean all
